--CREANDO LA BASE DE DATOS
CREATE DATABASE JORNADA_DE_VACUNACION

--USANDO LA BASE DE DATOS
USE JORNADA_DE_VACUNACION

--CREANDO LAS TABLAS
CREATE TABLE VACUNAS(
ID_VACUNA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_VACUNA NVARCHAR(20) NOT NULL,
CANTIDAD_VACUNA_RESTANTE INT NULL,
CANTIDAD_VACUNA_PUESTA INT NULL
--ESTABLECIENDO CAMPO UNICO
CONSTRAINT NOMBRE_VACUNA_UNICO UNIQUE(NOMBRE_VACUNA)
)

CREATE TABLE PROVINCIAS(
ID_PROVINCIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_PROVINCIA NVARCHAR(30) NOT NULL
--ESTABLECIENDO CAMPO UNICO
CONSTRAINT NOMBRE_PROVINCIA_UNICO UNIQUE(NOMBRE_PROVINCIA)
)

CREATE TABLE VACUNACION(
ID_VACUNACION INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CEDULA NVARCHAR(13) NOT NULL,
NOMBRES NVARCHAR(30) NOT NULL,
APELLIDOS NVARCHAR(30) NOT NULL,
TELEFONO NVARCHAR(12) NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
PROVINCIA NVARCHAR(30) NOT NULL,
VACUNA_RECIBIDA NVARCHAR(20) NOT NULL,
FECHA_PRIMERA_DOSIS DATE NOT NULL,
FECHA_SEGUNDA_DOSIS DATE NULL,
SIGNO_ZODIACAL NVARCHAR(15) NULL
--ESTABLECIENDO CAMPO UNICO
CONSTRAINT CEDULA_UNICO UNIQUE(CEDULA)
--ESTABLECIENDO LLAVES FORANEAS
CONSTRAINT FK_VACUNACION_VACUNA_RECIBIDA FOREIGN KEY(VACUNA_RECIBIDA) REFERENCES VACUNAS(NOMBRE_VACUNA),
CONSTRAINT FK_VACUNACION_PROVINCIA FOREIGN KEY(PROVINCIA) REFERENCES PROVINCIAS(NOMBRE_PROVINCIA)
)

--CREATE TABLE SIGNO_ZODIACALES(
--ID_ZODIACO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
--NOMBRE_ZODIACO NVARCHAR(15) NOT NULL,
--CANTIDAD_PACIENTES INT NULL
--)

--VISTAS DE TABLAS
SELECT *FROM VACUNACION
SELECT *FROM VACUNAS
SELECT *FROM PROVINCIAS
--SELECT *FROM SIGNO_ZODIACALES

--ELIMINAR TABLAS
DROP TABLE VACUNACION
DROP TABLE VACUNAS
DROP TABLE PROVINCIAS
--DROP TABLE SIGNO_ZODIACALES

--PROCEDIMIENTOS ALMACENADOS
GO 
CREATE PROCEDURE SP_AGREGAR_VACUNADO
@CEDULA NVARCHAR(13),
@NOMBRES NVARCHAR(30),
@APELLIDOS NVARCHAR(30),
@TELEFONO NVARCHAR(12),
@FECHA_DE_NACIMIENTO DATE,
@PROVINCIA NVARCHAR(30),
@VACUNA_RECIBIDA NVARCHAR(20),
@FECHA_PRIMERA_DOSIS DATE,
@FECHA_SEGUNDA_DOSIS DATE,
@SIGNO_ZODIACAL NVARCHAR(15)
AS
BEGIN
IF((SELECT CANTIDAD_VACUNA_RESTANTE FROM VACUNAS WHERE NOMBRE_VACUNA=@VACUNA_RECIBIDA)<1)
PRINT 'NO HAY VACUNAS'
ELSE IF (SELECT FECHA_PRIMERA_DOSIS FROM VACUNACION WHERE CEDULA = @CEDULA) IS NULL 
INSERT INTO VACUNACION(CEDULA,NOMBRES,APELLIDOS,TELEFONO,FECHA_DE_NACIMIENTO,PROVINCIA,VACUNA_RECIBIDA,FECHA_PRIMERA_DOSIS,SIGNO_ZODIACAL) 
VALUES (@CEDULA,@NOMBRES,@APELLIDOS,@TELEFONO,@FECHA_DE_NACIMIENTO,@PROVINCIA,@VACUNA_RECIBIDA,@FECHA_PRIMERA_DOSIS,@SIGNO_ZODIACAL)
ELSE
UPDATE VACUNACION SET FECHA_SEGUNDA_DOSIS=@FECHA_SEGUNDA_DOSIS WHERE CEDULA = @CEDULA
END

GO 
CREATE PROCEDURE SP_VALIDAR_VACUNADO
@CEDULA NVARCHAR(13)
AS
BEGIN
SELECT *FROM VACUNACION WHERE CEDULA=@CEDULA
END

GO
CREATE PROCEDURE SP_AGREGAR_PROVINCIA
@NOMBRE_PROVINCIA NVARCHAR(30)
AS
BEGIN
INSERT INTO PROVINCIAS VALUES(@NOMBRE_PROVINCIA)
END

GO 
CREATE PROCEDURE SP_MODIFICAR_PROVINCIA
@NOMBRE_PROVINCIA NVARCHAR(30),
@NOMBRE_NUEVO_PROVINCIA NVARCHAR(30)
AS
BEGIN
UPDATE PROVINCIAS SET NOMBRE_PROVINCIA=@NOMBRE_NUEVO_PROVINCIA WHERE NOMBRE_PROVINCIA=@NOMBRE_PROVINCIA
END

GO
CREATE PROCEDURE SP_AGREGAR_VACUNA_NUEVA
@NOMBRE_VACUNA NVARCHAR(20),
@CANTIDAD_VACUNA_RESTANTE INT,
@CANTIDAD_VACUNA_PUESTA INT
AS
BEGIN
INSERT VACUNAS VALUES(@NOMBRE_VACUNA,@CANTIDAD_VACUNA_RESTANTE,@CANTIDAD_VACUNA_PUESTA)
END
--GO
--CREATE PROCEDURE SP_AGREGAR_VACUNA_NUEVA
--@NOMBRE_VACUNA NVARCHAR(20),
--@CANTIDAD_VACUNA_RESTANTE INT
--AS
--BEGIN
--INSERT INTO VACUNAS VALUES(@NOMBRE_VACUNA,@CANTIDAD_VACUNA_RESTANTE)
--END

GO
CREATE PROCEDURE SP_AGREGAR_VACUNA_EXISTENTE
@NOMBRE_VACUNA NVARCHAR(20),
@CANTIDAD_VACUNA_RESTANTE INT
AS
BEGIN
DECLARE @CANTIDAD INT
SELECT @CANTIDAD = SUM(CANTIDAD_VACUNA_RESTANTE) +@CANTIDAD_VACUNA_RESTANTE FROM VACUNAS WHERE NOMBRE_VACUNA=@NOMBRE_VACUNA
UPDATE VACUNAS SET CANTIDAD_VACUNA_RESTANTE=@CANTIDAD WHERE NOMBRE_VACUNA=@NOMBRE_VACUNA
END

GO
CREATE PROCEDURE SP_BUSCAR_VACUNADOS_NOMBRE
@NOMBRES NVARCHAR(30)
AS
BEGIN
SELECT *FROM VACUNACION WHERE NOMBRES LIKE '%'+@NOMBRES+'%'
END

GO
CREATE PROCEDURE SP_BUSCAR_VACUNADOS_APELLIDO
@APELLIDOS NVARCHAR(30)
AS
BEGIN
SELECT *FROM VACUNACION WHERE APELLIDOS LIKE '%'+@APELLIDOS+'%'
END

GO 
CREATE PROCEDURE SP_BUSCAR_VACUNADOS_PROVINCIA
@PROVINCIA NVARCHAR(30)
AS
BEGIN
SELECT CEDULA,NOMBRES,APELLIDOS,TELEFONO,FECHA_PRIMERA_DOSIS,FECHA_SEGUNDA_DOSIS FROM VACUNACION WHERE PROVINCIA LIKE '%'+@PROVINCIA+'%' 
END

GO 
CREATE PROCEDURE SP_CANTIDAD_DE_PACIENTES_POR_VACUNA
@VACUNA_RECIBIDA NVARCHAR(20)
AS
BEGIN
SELECT COUNT(VACUNA_RECIBIDA) FROM VACUNACION WHERE VACUNA_RECIBIDA=@VACUNA_RECIBIDA
END

GO 
CREATE PROCEDURE SP_ELIMINAR_VACUNADO
@CEDULA NVARCHAR(13)
AS
BEGIN
DELETE FROM VACUNACION WHERE CEDULA=@CEDULA
END

GO
CREATE PROCEDURE SP_VALIDAR_SIGNO
@FECHA_DE_NACIMIENTO DATE
AS
BEGIN
IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 12 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>21)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 1 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<20)))
PRINT 'CAPRICORNIO'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 1 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>19)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 2 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<19)))
PRINT 'ACUARIO'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 2 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>18)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 3 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<21)))
PRINT 'PICIS'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 3 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>20)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 4 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<20)))
PRINT 'ARIES'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 4 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>19)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 5 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<21)))
PRINT 'TAURO'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 5 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>19)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 6 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<21)))
PRINT 'GEMINIS'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 6 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>20)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 7 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<23)))
PRINT 'CANCER' 
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 7 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>22)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 8 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<23)))
PRINT 'LEO'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 8 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>22)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 9 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<23)))
PRINT 'VIRGO'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 9 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>22)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 10 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<23)))
PRINT 'LIBRA'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 10 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>22)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 11 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<22)))
PRINT 'ESCORPIO'
ELSE IF(((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 11 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))>21)) OR ((SELECT MONTH(@FECHA_DE_NACIMIENTO)) = 12 AND ((SELECT DAY(@FECHA_DE_NACIMIENTO))<22)))
PRINT 'SAGITARIO'
END

--EJECUTAR PROCEDIMIENTOS ALMACENADOS
EXEC SP_AGREGAR_VACUNADO '4022R596','luis','pascual','6516515','1998/04/23','AZUA','CHINA','1998/04/23','1998/04/23','LIBRA'
EXEC SP_VALIDAR_VACUNADO '4022535964'
EXEC SP_AGREGAR_PROVINCIA 'AZUA'
EXEC SP_AGREGAR_VACUNA_NUEVA 'CHINA',1,0
EXEC SP_AGREGAR_VACUNA_EXISTENTE 'CHINA',10
EXEC SP_BUSCAR_VACUNADOS_NOMBRE 'l'
EXEC SP_BUSCAR_VACUNADOS_APELLIDO 'f'
EXEC SP_BUSCAR_VACUNADOS_PROVINCIA 'SAMANA'
EXEC SP_CANTIDAD_DE_PACIENTES_POR_VACUNA 'CHINA'
--mostrar todas las vacunas y la cantidad que se han puesto
EXEC SP_ELIMINAR_VACUNADO '40225359641'
EXEC SP_VALIDAR_SIGNO '1997/1/19'
EXEC SP_MODIFICAR_PROVINCIA 'AZUA','SEIBO'

--ELIMINAR PROCEDIMIENTOS ALMACENADOS
DROP PROCEDURE SP_AGREGAR_VACUNADO
DROP PROCEDURE SP_VALIDAR_VACUNADO
DROP PROCEDURE SP_AGREGAR_PROVINCIA
DROP PROCEDURE SP_AGREGAR_VACUNA_NUEVA
DROP PROCEDURE SP_AGREGAR_VACUNA_EXISTENTE
DROP PROCEDURE SP_BUSCAR_VACUNADOS_NOMBRE
DROP PROCEDURE SP_BUSCAR_VACUNADOS_APELLIDO
DROP PROCEDURE SP_BUSCAR_VACUNADOS_PROVINCIA
DROP PROCEDURE SP_CANTIDAD_DE_PACIENTES_POR_VACUNA
DROP PROCEDURE SP_ELIMINAR_VACUNADO
--DROP PROCEDURE SP_VALIDAR_SIGNO
DROP PROCEDURE SP_MODIFICAR_PROVINCIA

--CREANDO TRIGGERS
GO
CREATE TRIGGER TR_INVENTARIO_VACUNACION1
ON VACUNACION FOR INSERT
AS
BEGIN
DECLARE @NOMBRE_VACUNA NVARCHAR(20)
SELECT @NOMBRE_VACUNA = VACUNA_RECIBIDA FROM inserted
UPDATE VACUNAS SET CANTIDAD_VACUNA_RESTANTE = (CANTIDAD_VACUNA_RESTANTE-1) WHERE NOMBRE_VACUNA=@NOMBRE_VACUNA
UPDATE VACUNAS SET CANTIDAD_VACUNA_PUESTA = (CANTIDAD_VACUNA_PUESTA+1) WHERE NOMBRE_VACUNA=@NOMBRE_VACUNA
END

GO
CREATE TRIGGER TR_INVENTARIO_VACUNACION2
ON VACUNACION FOR UPDATE
AS
BEGIN
DECLARE @NOMBRE_VACUNA NVARCHAR(20)
SELECT @NOMBRE_VACUNA = VACUNA_RECIBIDA FROM inserted
UPDATE VACUNAS SET CANTIDAD_VACUNA_RESTANTE = (CANTIDAD_VACUNA_RESTANTE-1) WHERE NOMBRE_VACUNA=@NOMBRE_VACUNA
UPDATE VACUNAS SET CANTIDAD_VACUNA_PUESTA = (CANTIDAD_VACUNA_PUESTA+1) WHERE NOMBRE_VACUNA=@NOMBRE_VACUNA
END


--GO
--CREATE TRIGGER TR_SIGNO_ZODIACAL_INSERTADO
--ON VACUNACION FOR INSERT
--AS
--declare @SIGNO_ZODIACAL NVARCHAR(15)
--SELECT @SIGNO_ZODIACAL = SIGNO_ZODIACAL FROM inserted
--DECLARE @ZODIACO INT
--SELECT @ZODIACO = SUM(CANTIDAD_PACIENTES) +1 FROM SIGNO_ZODIACALES WHERE NOMBRE_ZODIACO=@SIGNO_ZODIACAL
--UPDATE SIGNO_ZODIACALES SET CANTIDAD_PACIENTES=@ZODIACO WHERE NOMBRE_ZODIACO=@SIGNO_ZODIACAL

--BORRANDO TRIGGERS
DROP TRIGGER TR_INVENTARIO_VACUNACION1
DROP TRIGGER TR_INVENTARIO_VACUNACION2

--DATOS PARA INICIAR LA TABLA DE SIGNOS ZODIACALES
--INSERT INTO SIGNO_ZODIACALES VALUES('ACUARIO',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('PICIS',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('ARIES',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('TAURO',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('GEMINIS',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('CANCER',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('LEO',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('VIRGO',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('LIBRA',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('ESCORPIO',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('SAGITARIO',0)
--INSERT INTO SIGNO_ZODIACALES VALUES('CAPRICORNIO',0)

